# Generated by Django 5.1.1 on 2024-11-25 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHEM', '0002_medico_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favoritos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHEM.medico')),
                ('cpf_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHEM.paciente')),
            ],
        ),
    ]
