# Generated by Django 5.1.1 on 2024-11-26 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appHEM', '0006_delete_mensagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=11)),
                ('conteudo', models.TextField(max_length=250)),
                ('horario', models.TimeField(auto_now=True)),
                ('cpf_med', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHEM.medico')),
                ('cpf_pac', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appHEM.paciente')),
            ],
        ),
    ]
